cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 35.228.195.195.nip.io
    exposer: Ingress
    http: "true"
global:
  extraEnv: |
    # - name: SERVER_USEFORWARDHEADERS
    #   value: "true"
    # - name: SERVER_TOMCAT_INTERNALPROXIES
    #   value: ".*"
    # - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    #   value: "*"
  gateway:
    annotations:
      certmanager.k8s.io/issuer: letsencrypt-prod
    domain: 35.228.195.195.nip.io
    host: gateway.{{ .Release.Namespace }}.{{ template "common.gateway-domain" . }}
    http: "true"
    tlsacme: "false"
  keycloak:
    client: activiti
    extraEnv: "# - name: KEYCLOAK_USERESOURCEROLEMAPPINGS\n#   value: \"false\" \n"
    host: identity.{{ .Release.Namespace }}.{{ template "common.gateway-domain" .
      }}
    realm: activiti
    resource: activiti
    url: ""
  registryPullSecrets: []
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system
